### ISSUE TITLE
Error: Invalid URL for SignPath API

### ISSUE THREAD

**Issue by r-lyeh** [SignPath/github-action-submit-signing-request#11]
New error `Error: Invalid URL for SignPath API` while trying to cert some binaries.
Has the connector-url string changed recently?
This used to work as-is last time I signed a release (May 31, 2025).

```yaml
Run signpath/github-action-submit-signing-request@v1.1
  with:
    api-token: ***
    organization-id: ***
    project-slug: spectral
    signing-policy-slug: release-signing
    github-artifact-id: 3418[2](https://github.com/r-lyeh/Spectral/actions/runs/15924551189/job/44918748589#step:5:2)54532
    wait-for-completion: true
    wait-for-completion-timeout-in-seconds: 10800
    output-artifact-directory: signed/
    connector-url: https://githubactions.connectors.signpath.io
    github-token: ***
    service-unavailable-timeout-in-seconds: 600
    download-signed-artifact-timeout-in-seconds: [3](https://github.com/r-lyeh/Spectral/actions/runs/15924551189/job/44918748589#step:5:3)00
Submitting the signing request to SignPath CI connector...
Error: Invalid URL for SignPath API
```
