### ISSUE TITLE
Trusted build system cannot be used in conjunction with an interactive user

### ISSUE THREAD

**Issue by mlocati** [SignPath/github-action-submit-signing-request#3]
I've just got a SignPath FOSS account (thanks❤️!).

I see that the SignPath account is already configured, and everything seems to be ready to be used (at least for testing).

I've created this job step ([see here](https://github.com/mlocati/gettext-iconv-windows/pull/18)):

```yml
      -
        name: Sign zip
        id: sign-zip
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: 98c3accc-92c9-4962-b150-ff1f5c6356b8
          project-slug: gettext-iconv-windows
          signing-policy-slug: test-signing
          github-artifact-id: ${{ steps.upload-zip.outputs.artifact-id }}
          wait-for-completion: true
          output-artifact-directory: C:\
```

But the step fails with the following error:

```
Submitting the signing request to SignPath CI connector...
Error: Could not authorize against SignPath API. Trusted build system cannot be used in conjunction with an interactive user.
```

I don't know how to proceed.

PS: In the SighPath dashboard, under the gettext-iconv-windows Project > test-signingSigning Policy I see this:
   ![immagine](https://github.com/user-attachments/assets/c9646d11-7d07-4764-9d7a-71fd7d969fe6)
