### ISSUE TITLE
Invalid URL for SignPath API. https://sp-app-prod-ingress-api.sp-prod.svc.cluster.local/Api/v1-pre/***/Organization

### ISSUE THREAD

**Issue by buffge** [SignPath/github-action-submit-signing-request#5]
My config is 
```
- name: sign
  uses: SignPath/github-action-submit-signing-request@v1
  with:
    api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
    organization-id: '${{ secrets.SIGNPATH_ORG_ID }}'
    project-slug: 'hh-lol-prophet-test'
    signing-policy-slug: 'test'
    github-artifact-id: '${{steps.uploadArtifact.outputs.artifact-id}}'
    wait-for-completion: true
    output-artifact-directory: 'bin'
    parameters: |
      Version: "${{ github.ref_name }}"
```
job url is https://github.com/real-web-world/hh-lol-prophet/actions/runs/11777982154/job/32803462912
